[workspace]
members = [
    "node",
    "node-cli"
]

[workspace.dependencies]
nymlib = { git = "https://github.com/valansai/nymlib", branch = "main" }
tokio = { version = "1", features = ["full"] }
simplelog = "0.12"
log = "0.4"