[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
nymlib = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
lmdb = "0.8.0"